repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: debug-statements
      - id: mixed-line-ending

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.3
    hooks:
      - id: pyupgrade
        args:
          - '--py37-plus'

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black-jupyter

  - repo: https://github.com/keewis/blackdoc
    rev: v0.3.5
    hooks:
      - id: blackdoc

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.2
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.4.0
    hooks:
      # - id: nbqa-black
      #   additional_dependencies: [black==21.7b0]
      #   exclude: posts/2021/function-expressions-in-js.ipynb
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==2.31.0]
        exclude: posts/2021/function-expressions-in-js.ipynb
      - id: nbqa-isort
        additional_dependencies: [isort==5.10.1]
        exclude: posts/2021/function-expressions-in-js.ipynb

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
