# Site settings
title: Home of Banihirwe Anderson >>
header-img: img/home.jpg
email: axbanihirwe@gmail.com
copyright_name: Your/Project/Corporate Name
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "https://andersy005.github.io/"
url: "https://andersy005.github.io/"
twitter_username: andersy005
github_username:  andersy005
facebook_username: None
email_username:  axbanihirwe@gmail.com 

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
