name: blog
channels:
  - conda-forge
  - nodefaults
dependencies:
  - ablog
  - cftime
  - colorspacious
  - dask
  - dask-labextension
  - distributed
  - hvplot
  - ipywidgets
  - ipywidgets
  - jupyterlab>=3
  - matplotlib
  - myst-nb>=0.12.0
  - netcdf4
  - numba
  - pip
  - pydantic
  - pydata-sphinx-theme>=0.4.3
  - python=3.9
  - scipy
  - seaborn
  - sphinx
  - sphinx-autobuild
  - sphinx-comments
  - sphinx-panels
  - sphinxcontrib-bibtex<2.0.0
  - sympy
  - watermark
  - wrapt
  - xarray>=0.18.2
  - pooch
  - pip:
      - ptime
      - sphinxext-opengraph
