name: blog
channels:
  - conda-forge
  - nodefaults
dependencies:
  - ablog
  - cftime
  - colorspacious
  - dask
  - dask-labextension
  - distributed
  - hvplot
  - ipywidgets
  - jupyterlab
  - matplotlib
  - myst-nb
  - netcdf4
  - numba
  - pydantic
  - pydata-sphinx-theme>=0.4.3
  - python=3.12
  - scipy
  - seaborn
  - sphinx
  - sphinx-autobuild
  - sphinx-comments
  - sphinx-panels
  - sphinxcontrib-bibtex
  - sympy
  - watermark
  - wrapt
  - xarray
  - pooch
  - pip:
      - ptime
      - sphinx-design
      - sphinxext-opengraph
