name: playground
channels:
  - conda-forge
dependencies:
  - hvplot
  - ipywidgets
  - jupyterlab
  - matplotlib
  - nodejs
  - numpy
  - pandas
  - panel
  - proplot
  - python=3.8
  - scikit-image
  - scikit-learn
  - watermark
  - xarray
